#!/bin/sh

#  -------------------------------------------------------------------------
#  Copyright (C) 2018 BMW Car IT GmbH
#  -------------------------------------------------------------------------
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
#  -------------------------------------------------------------------------

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>

SDKROOT=$(pwd)

has_error=0
IFS=' '
while read local_ref local_sha remote_ref remote_sha
do
    echo "Check pushing of ${local_sha}"
    ${SDKROOT}/scripts/commit-checks/check_all_commit_rules.py "${local_sha}"
    if [ $? != 0 ]; then has_error=1; fi
    echo "\n"
done

if [ $has_error != 0 ]; then
    echo "ERROR: Commit rule checker prevented pushing"
    exit 1
fi

exit 0
